version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: composer install

      # Add more steps for testing, linting, etc.

workflows:
  version: 2
  build:
    jobs:
      - build
