---
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:7.4
    steps:
      - checkout
      - run:
          name: Install Composer dependencies
          command: composer install
      - run:
          name: Run PHPUnit tests
          command: vendor/bin/phpunit
workflows:
  version: 2
  build:
    jobs:
      - build
