---
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-apache
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup Project
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip
            curl -sS https://getcomposer.org/installer | php
            sudo mv composer.phar /usr/local/bin/composer
            composer install --no-dev --optimize-autoloader
            composer install
      - run:
          name: Start Apache
          command: |
            sudo service apache2 start
            sleep 10 # Give Apache some time to start
      - run:
          name: Check Apache Logs
          command: |
            sudo cat /var/log/apache2/error.log
            sudo cat /var/log/apache2/access.log

      - run:
          name: Check Website
          command: curl -I http://192.168.160.3 
      - run:
          name: Check Apache Status
          command: sudo service apache2 status

  deploy:
    docker:
      - image: circleci/php:7.4-apache
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Deploy to Production
          command: |
            sudo cp hostel/index.php /var/www/html/
            sudo service apache2 restart
                   
                   
            
workflows:
  version: 3
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
